Retry git clone if it fails

diff --git a/workflows/build-initial.yaml b/workflows/build-initial.yaml
--- a/workflows/build-initial.yaml
+++ b/workflows/build-initial.yaml
@@ -27,11 +27,21 @@ spec:
       command: [sh, -c]
       args:
         - |
-          for i in {1..5}; do
+          MAX_RETRIES=5
+          i=1
+
+          while [ $i -le $MAX_RETRIES ]; do
+            echo "Attempt $i of $MAX_RETRIES: Cloning repo..."
             git clone --branch master https://github.com/teaching-on-testbeds/gourmetgram.git /mnt/workspace && break
-            echo "Git clone failed. Retrying in 5 seconds... ($i/5)"
+            echo "Git clone failed. Retrying in 5 seconds..."
+            i=$((i + 1))
             sleep 5
           done
+
+          if [ ! -d /mnt/workspace/.git ]; then
+            echo "Git clone failed after $MAX_RETRIES attempts."
+            exit 1
+          fi
       volumeMounts:
       - name: workdir
         mountPath: /mnt/workspace
@@ -39,9 +49,6 @@ spec:
   - name: kaniko
     container:
       image: gcr.io/kaniko-project/executor:latest
-      resources:
-        requests:
-          memory: "1500Mi"
       args:
         - --dockerfile=/mnt/workspace/Dockerfile
         - --context=/mnt/workspace
@@ -50,6 +57,6 @@ spec:
         - --destination=registry.kube-system.svc.cluster.local:5000/gourmetgram-app:production-1.0.0
         - --insecure
       volumeMounts:
-      - name: workdir
-        mountPath: /mnt/workspace
+        - name: workdir
+          mountPath: /mnt/workspace
 
